language: ruby

script:
  - env
  - set -o pipefail
  - bundle install
  - curl -o tr-reporter https://downloads.testrecall.com/r/latest/reporter.linux-amd64
  - chmod +x tr-reporter

  - gem install rspec_junit_formatter
  - bundle exe2c rspec --format RspecJunitFormatter --out report.xml | ./tr-reporter -file report.xml
