language: go

script:
  - go get -u github.com/jstemmer/go-junit-report
  - curl -o testrecall-uploader https://s3.amazonaws.com/releases.testrecall.com/testrecall-uploader
  - chmod +x testrecall-uploader

  - ./test_golang.sh
