version: 2.1
jobs:
  build:
    working_directory: ~/tr-example
    docker:
      - image: circleci/ruby:2.6.4

      - run:
          name: Run Rspec automated tests
          command: |
            curl -o tr-reporter https://downloads.testrecall.com/r/latest/reporter.linux-amd64
            chmod +x tr-reporter

            gem install rspec_junit_formatter
            bundle exec rspec --format RspecJunitFormatter --out rspec.xml | ./tr-reporter -file rspec.xml
