version: 2.1
jobs:
  build:
    working_directory: ~/tre
    docker:
      - image: circleci/ruby:2.6.4
        environment:
          RAILS_ENV: test

    steps:
      - checkout
      - restore_cache:
          name: Restore Ruby dependencies from cache
          key: gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          name: Cache Ruby dependencies
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Rspec automated tests
          command: |
            curl -o tr-reporter https://downloads.testrecall.com/r/latest/reporter.linux-amd64
            chmod +x tr-reporter

            gem install rspec_junit_formatter
            bundle exec rspec --format RspecJunitFormatter --out rspec.xml | ./reporter -file rspec.xml
